# Generated by Django 5.1.1 on 2024-10-06 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_blogs_options_alter_blogs_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='categor',
            new_name='category',
        ),
    ]
